// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erjcjemicnyfezgzfoxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyamNqZW1pY255ZmV6Z3pmb3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1ODgzMDUsImV4cCI6MjEwNjE2NDMwNX0.mbUm4UD12kznHmxUOKQmB4bPPkCn0FBfYOJtvQt-dvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});